<?php

namespace Database\Seeders;

use App\Models\Lgu;
use Illuminate\Database\Seeder;

class LguSeeder extends Seeder
{
    public function run(): void
    {
        $lgus = [
            // ==========================================
            // 1ST CONGRESSIONAL DISTRICT (6 LGUs)
            // ==========================================
            [
                'lgu_id' => 'cabusao',
                'name' => 'Cabusao',
                'district' => '1st District',
                'class' => '5th Class Municipality',
                'area' => '46.80 km²',
                'pop' => '19,200',
                'map_url' => 'https://maps.google.com/maps?q=Cabusao+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/cabusao.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'delgallego',
                'name' => 'Del Gallego',
                'district' => '1st District',
                'class' => '4th Class Municipality',
                'area' => '208.84 km²',
                'pop' => '26,700',
                'map_url' => 'https://maps.google.com/maps?q=Del+Gallego+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/delgallego.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'libmanan',
                'name' => 'Libmanan',
                'district' => '1st District',
                'class' => '1st Class Municipality (Largest Area)',
                'area' => '342.82 km²',
                'pop' => '116,100',
                'map_url' => 'https://maps.google.com/maps?q=Libmanan+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/libmanan.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'lupi',
                'name' => 'Lupi',
                'district' => '1st District',
                'class' => '3rd Class Municipality',
                'area' => '199.12 km²',
                'pop' => '34,500',
                'map_url' => 'https://maps.google.com/maps?q=Lupi+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/lupi.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'ragay',
                'name' => 'Ragay',
                'district' => '1st District',
                'class' => '1st Class Municipality',
                'area' => '400.22 km²',
                'pop' => '61,800',
                'map_url' => 'https://maps.google.com/maps?q=Ragay+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/ragay.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'sipocot',
                'name' => 'Sipocot',
                'district' => '1st District',
                'class' => '1st Class Municipality',
                'area' => '243.43 km²',
                'pop' => '70,200',
                'map_url' => 'https://maps.google.com/maps?q=Sipocot+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/sipocot.png',
                'evac_centers' => 2,
            ],

            // ==========================================
            // 2ND CONGRESSIONAL DISTRICT (7 LGUs)
            // ==========================================
            [
                'lgu_id' => 'gainza',
                'name' => 'Gainza',
                'district' => '2nd District',
                'class' => '5th Class Municipality',
                'area' => '14.75 km²',
                'pop' => '11,800',
                'map_url' => 'https://maps.google.com/maps?q=Gainza+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/gainza.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'milaor',
                'name' => 'Milaor',
                'district' => '2nd District',
                'class' => '3rd Class Municipality',
                'area' => '33.64 km²',
                'pop' => '34,900',
                'map_url' => 'https://maps.google.com/maps?q=Milaor+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/milaor.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'minalabac',
                'name' => 'Minalabac',
                'district' => '2nd District',
                'class' => '2nd Class Municipality',
                'area' => '126.10 km²',
                'pop' => '56,200',
                'map_url' => 'https://maps.google.com/maps?q=Minalabac+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/minalabac.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'pamplona',
                'name' => 'Pamplona',
                'district' => '2nd District',
                'class' => '3rd Class Municipality',
                'area' => '80.60 km²',
                'pop' => '37,900',
                'map_url' => 'https://maps.google.com/maps?q=Pamplona+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/pamplona.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'pasacao',
                'name' => 'Pasacao',
                'district' => '2nd District',
                'class' => '3rd Class Municipality',
                'area' => '149.54 km²',
                'pop' => '51,400',
                'map_url' => 'https://maps.google.com/maps?q=Pasacao+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/pasacao.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'pili',
                'name' => 'Pili (Provincial Capital)',
                'district' => '2nd District',
                'class' => '1st Class Municipality',
                'area' => '290.25 km²',
                'pop' => '102,100',
                'map_url' => 'https://maps.google.com/maps?q=Pili+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/pili.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'sanfernando',
                'name' => 'San Fernando',
                'district' => '2nd District',
                'class' => '2nd Class Municipality',
                'area' => '117.63 km²',
                'pop' => '38,600',
                'map_url' => 'https://maps.google.com/maps?q=San+Fernando+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/sanfernando.png',
                'evac_centers' => 2,
            ],

            // ==========================================
            // 3RD CONGRESSIONAL DISTRICT (7 LGUs)
            // ==========================================
            [
                'lgu_id' => 'bombon',
                'name' => 'Bombon',
                'district' => '3rd District',
                'class' => '4th Class Municipality',
                'area' => '28.73 km²',
                'pop' => '17,800',
                'map_url' => 'https://maps.google.com/maps?q=Bombon+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/bombon.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'calabanga',
                'name' => 'Calabanga',
                'district' => '3rd District',
                'class' => '1st Class Municipality',
                'area' => '163.80 km²',
                'pop' => '91,400',
                'map_url' => 'https://maps.google.com/maps?q=Calabanga+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/calabanga.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'camaligan',
                'name' => 'Camaligan',
                'district' => '3rd District',
                'class' => '5th Class Municipality (Smallest Area)',
                'area' => '4.68 km²',
                'pop' => '25,100',
                'map_url' => 'https://maps.google.com/maps?q=Camaligan+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/camaligan.png',
                'evac_centers' => 1,
            ],
            [
                'lgu_id' => 'canaman',
                'name' => 'Canaman',
                'district' => '3rd District',
                'class' => '3rd Class Municipality',
                'area' => '43.27 km²',
                'pop' => '37,200',
                'map_url' => 'https://maps.google.com/maps?q=Canaman+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/canaman.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'magarao',
                'name' => 'Magarao',
                'district' => '3rd District',
                'class' => '4th Class Municipality',
                'area' => '44.97 km²',
                'pop' => '27,300',
                'map_url' => 'https://maps.google.com/maps?q=Magarao+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/magarao.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'naga',
                'name' => 'Naga City',
                'district' => '3rd District',
                'class' => 'Independent Component City',
                'area' => '84.48 km²',
                'pop' => '215,400',
                'map_url' => 'https://maps.google.com/maps?q=Naga+City+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/naga.png',
                'evac_centers' => 4,
            ],
            [
                'lgu_id' => 'ocampo',
                'name' => 'Ocampo',
                'district' => '3rd District',
                'class' => '3rd Class Municipality',
                'area' => '118.33 km²',
                'pop' => '52,800',
                'map_url' => 'https://maps.google.com/maps?q=Ocampo+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/ocampo.png',
                'evac_centers' => 2,
            ],

            // ==========================================
            // 4TH CONGRESSIONAL DISTRICT / PARTIDO (10 LGUs)
            // ==========================================
            [
                'lgu_id' => 'caramoan',
                'name' => 'Caramoan',
                'district' => '4th District',
                'class' => '2nd Class Municipality',
                'area' => '277.41 km²',
                'pop' => '53,200',
                'map_url' => 'https://maps.google.com/maps?q=Caramoan+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/caramoan.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'garchitorena',
                'name' => 'Garchitorena',
                'district' => '4th District',
                'class' => '4th Class Municipality',
                'area' => '243.80 km²',
                'pop' => '29,400',
                'map_url' => 'https://maps.google.com/maps?q=Garchitorena+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/garchitorena.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'goa',
                'name' => 'Goa',
                'district' => '4th District',
                'class' => '1st Class Municipality',
                'area' => '206.18 km²',
                'pop' => '73,600',
                'map_url' => 'https://maps.google.com/maps?q=Goa+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/goa.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'lagonoy',
                'name' => 'Lagonoy',
                'district' => '4th District',
                'class' => '2nd Class Municipality',
                'area' => '377.90 km²',
                'pop' => '58,400',
                'map_url' => 'https://maps.google.com/maps?q=Lagonoy+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/lagonoy.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'presentacion',
                'name' => 'Presentacion',
                'district' => '4th District',
                'class' => '4th Class Municipality',
                'area' => '143.80 km²',
                'pop' => '22,600',
                'map_url' => 'https://maps.google.com/maps?q=Presentacion+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/presentacion.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'sagnay',
                'name' => 'Sagnay',
                'district' => '4th District',
                'class' => '4th Class Municipality',
                'area' => '154.19 km²',
                'pop' => '36,400',
                'map_url' => 'https://maps.google.com/maps?q=Sagnay+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/sagnay.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'sanjose',
                'name' => 'San Jose',
                'district' => '4th District',
                'class' => '4th Class Municipality',
                'area' => '43.07 km²',
                'pop' => '42,100',
                'map_url' => 'https://maps.google.com/maps?q=San+Jose+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/sanjose.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'siruma',
                'name' => 'Siruma',
                'district' => '4th District',
                'class' => '4th Class Municipality',
                'area' => '141.27 km²',
                'pop' => '19,800',
                'map_url' => 'https://maps.google.com/maps?q=Lupi+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed6',
                'seal' => '/img/icons/quickfacts/muns/siruma.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'tigaon',
                'name' => 'Tigaon',
                'district' => '4th District',
                'class' => '1st Class Municipality',
                'area' => '72.35 km²',
                'pop' => '60,500',
                'map_url' => 'https://maps.google.com/maps?q=Tigaon+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/tigaon.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'tinambac',
                'name' => 'Tinambac',
                'district' => '4th District',
                'class' => '1st Class Municipality',
                'area' => '351.62 km²',
                'pop' => '73,900',
                'map_url' => 'https://maps.google.com/maps?q=Tinambac+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/tinambac.png',
                'evac_centers' => 2,
            ],

            // ==========================================
            // 5TH CONGRESSIONAL DISTRICT (7 LGUs)
            // ==========================================
            [
                'lgu_id' => 'baao',
                'name' => 'Baao',
                'district' => '5th District',
                'class' => '1st Class Municipality',
                'area' => '106.50 km²',
                'pop' => '61,300',
                'map_url' => 'https://maps.google.com/maps?q=Baao+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/baao.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'balatan',
                'name' => 'Balatan',
                'district' => '5th District',
                'class' => '4th Class Municipality',
                'area' => '93.09 km²',
                'pop' => '31,800',
                'map_url' => 'https://maps.google.com/maps?q=Balatan+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/balatan.png',
                'evac_centers' => 1,
            ],
            [
                'lgu_id' => 'bato',
                'name' => 'Bato',
                'district' => '5th District',
                'class' => '3rd Class Municipality',
                'area' => '107.12 km²',
                'pop' => '53,900',
                'map_url' => 'https://maps.google.com/maps?q=Bato+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/bato.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'buhi',
                'name' => 'Buhi',
                'district' => '5th District',
                'class' => '1st Class Municipality',
                'area' => '246.65 km²',
                'pop' => '84,500',
                'map_url' => 'https://maps.google.com/maps?q=Buhi+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/buhi.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'bula',
                'name' => 'Bula',
                'district' => '5th District',
                'class' => '1st Class Municipality',
                'area' => '167.64 km²',
                'pop' => '72,100',
                'map_url' => 'https://maps.google.com/maps?q=Bula+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/bula.png',
                'evac_centers' => 2,
            ],
            [
                'lgu_id' => 'iriga',
                'name' => 'Iriga City',
                'district' => '5th District',
                'class' => 'Component City',
                'area' => '137.35 km²',
                'pop' => '118,200',
                'map_url' => 'https://maps.google.com/maps?q=Iriga+City+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/iriga.png',
                'evac_centers' => 3,
            ],
            [
                'lgu_id' => 'nabua',
                'name' => 'Nabua',
                'district' => '5th District',
                'class' => '1st Class Municipality',
                'area' => '88.54 km²',
                'pop' => '86,800',
                'map_url' => 'https://maps.google.com/maps?q=Nabua+Camarines+Sur&t=&z=13&ie=UTF8&iwloc=&output=embed',
                'seal' => '/img/icons/quickfacts/muns/nabua.png',
                'evac_centers' => 2,
            ],
        ];

        foreach ($lgus as $lguData) {
            Lgu::updateOrCreate(
                ['lgu_id' => $lguData['lgu_id']],
                $lguData
            );
        }
    }
}
