<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PastGovernorsSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $governors = [
            [
                'order_no' => 1,
                'name' => 'Mariano Abella',
                'image_path' => 'img/about/past-governors/Mariano Abella.png',
                'term_start_year' => 1898,
                'term_end_year' => 1900,
                'party' => json_encode([
                    ['term' => '1898–1900', 'party' => null],
                    ['term' => '1906–1909', 'party' => 'Progresista']
                ]),
                'era' => 'Revolutionary Government',
                'era_start_year' => 1898,
                'era_end_year' => 1900,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Mariano Abella is recognized as the first Filipino provincial leader under the Revolutionary Government of President Emilio Aguinaldo, who served from December 1898 to February 1900 based on NCCA/CulturEd records. He is also among the representatives of Ambos Camarines in the Malolos Congress. A few years later, he again served as governor under the American civil government (1906–1909), so he was able to serve in two different periods of history. There is no documented date of birth or age recorded in reliable national or regional archives for Mariano Abella, so the age-related fields are set to null. Local records about this period are also limited because the original documents of the Revolutionary Government are housed in national and foreign archives, and part of the records were also lost during World War II and the fire in the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Mariano Abella ang kinikilalang unang Pilipinong pinuno ng lalawigan sa ilalim ng Rebolusyonaryong Pamahalaan ni Pangulong Emilio Aguinaldo, na naglingkod mula Disyembre 1898 hanggang Pebrero 1900 batay sa mga tala ng NCCA/CulturEd. Kabilang din siya sa mga kinatawan ng Ambos Camarines sa Malolos Congress. Pagkalipas ng ilang taon, muli siyang naglingkod bilang gobernador sa ilalim ng pamahalaang sibil ng mga Amerikano (1906–1909), kaya siya ay nakapaglingkod sa dalawang magkaibang panahon ng kasaysayan. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga mapagkakatiwalaang pambansang o rehiyonal na archives para kay Mariano Abella, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado rin ang lokal na tala tungkol sa panahong ito dahil ang mga orihinal na dokumento ng Rebolusyonaryong Pamahalaan ay nakalagak sa mga pambansa at dayuhang archives, at bahagi rin ng mga tala ang nawala noong Ikalawang Digmaang Pandaigdig at sa sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Kinikilala bilang unang Pilipinong gobernador ng Camarines sa historical continuity basis (NCCA/NHCP).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 2,
                'name' => 'George Curry',
                'image_path' => 'img/about/past-governors/George Curry.png',
                'term_start_year' => 1901,
                'term_end_year' => 1901,
                'party' => json_encode([
                    ['term' => '1901', 'party' => 'Republican']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => 40,
                'age_at_return' => null,
                'description_en' => 'George Curry (born April 3, 1861) was an American soldier and administrator who became the first civil governor of Ambos Camarines in 1901 under American civil government. He was a veteran of the Spanish-American War as a member of Theodore Roosevelt\'s Rough Riders. His tenure in the province was short — only a few months — before he was transferred to Manila where he served in the police, and later became the governor of another province in the Philippines. After he returned to the United States, he became the Territorial Governor of New Mexico. His tenure began the formal transition from military rule to civil government in the province.',
                'description_tl' => 'Si George Curry (ipinanganak noong Abril 3, 1861) ay isang Amerikanong sundalo at administrador na naging unang civil governor ng Ambos Camarines noong 1901 sa ilalim ng pamahalaang sibil ng mga Amerikano. Siya ay beterano ng Spanish-American War bilang miyembro ng Rough Riders ni Theodore Roosevelt. Maikli lamang ang kanyang panunungkulan sa lalawigan — mga ilang buwan lamang — bago siya inilipat sa Maynila kung saan siya nanungkulan sa pulisya, at kalaunan ay naging gobernador pa ng ibang lalawigan sa Pilipinas. Pagkabalik niya sa Estados Unidos, siya ay naging Territorial Governor ng New Mexico. Ang kanyang panunungkulan ang nagsimula ng pormal na transisyon mula sa military rule patungo sa pamahalaang sibil sa lalawigan.',
                'notes' => 'Unang American civil governor ng Ambos Camarines. Isa sa pinakamaikling termino (ilang buwan lang, 1901).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 3,
                'name' => 'James Ross',
                'image_path' => 'img/about/past-governors/James Ross.png',
                'term_start_year' => 1901,
                'term_end_year' => 1903,
                'party' => json_encode([
                    ['term' => '1901–1903', 'party' => 'Republican']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'James Ross was an American who served as governor of Ambos Camarines from 1901 to 1903, succeeding George Curry. He continued to establish civil government structures in the province in the early years of the American era. There is no documented date of birth or age recorded in reliable sources for James Ross, so the age-related fields are set to null. Local records about this period are limited because part of the records were lost during World War II and the fire in the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si James Ross ay Amerikanong naglingkod bilang gobernador ng Ambos Camarines mula 1901 hanggang 1903, kasunod ni George Curry. Ipinagpatuloy niya ang pagtatatag ng mga istruktura ng pamahalaang sibil sa lalawigan sa unang mga taon ng panahon ng mga Amerikano. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay James Ross, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga lokal na tala tungkol sa panahong ito dahil bahagi ng mga tala ang nawala noong Ikalawang Digmaang Pandaigdig at sa sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 4,
                'name' => 'Juan Pimentel',
                'image_path' => 'img/about/past-governors/Juan Pimentel.png',
                'term_start_year' => 1903,
                'term_end_year' => 1906,
                'party' => json_encode([
                    ['term' => '1903–1906', 'party' => 'Federalista']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Juan Pimentel was the first Filipino to become the civil governor of Ambos Camarines under the American government, serving from 1903 to 1906. He was a member of the Federalist Party. His sitting was an important step in the gradual transfer of the leadership of the province to the Filipinos within the colonial system of the Americans. There is no documented date of birth or age recorded in reliable sources for Juan Pimentel, so the age-related fields are set to null. Local records about this period are limited because the original documents are housed in national and foreign archives, and part of the records were also lost during World War II and the fire in the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Juan Pimentel ang unang Pilipinong naging civil governor ng Ambos Camarines sa ilalim ng pamahalaang Amerikano, na naglingkod mula 1903 hanggang 1906. Miyembro siya ng Partido Federalista. Ang kanyang pagkakaupo ay mahalagang hakbang sa unti-unting paglilipat ng pamumuno ng lalawigan sa mga Pilipino sa loob ng sistemang kolonyal ng mga Amerikano. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Juan Pimentel, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga lokal na tala tungkol sa panahong ito dahil ang mga orihinal na dokumento ay nakalagak sa mga pambansa at dayuhang archives, at bahagi rin ng mga tala ang nawala noong Ikalawang Digmaang Pandaigdig at sa sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Unang Pilipinong civil governor ng Ambos Camarines sa ilalim ng pamahalaang Amerikano.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 5,
                'name' => 'Mariano Abella',
                'image_path' => 'img/about/past-governors/Mariano Abella.png',
                'term_start_year' => 1906,
                'term_end_year' => 1909,
                'party' => json_encode([
                    ['term' => '1898–1900', 'party' => null],
                    ['term' => '1906–1909', 'party' => 'Progresista']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'This is the second tenure of Mariano Abella as the head of the province — the first was during the Revolutionary Government (1898–1900). This time, he served under the American civil government from 1906 to 1909 as a member of the Progressive Party. He is one of the few provincial leaders who served in two different regimes — from the revolutionary Philippine government to the American colonial government. There is no documented date of birth or age recorded in the reliable archives for Mariano Abella, so the fields related to age (in both first term and return) are set to null. Local records about this period are also limited because part of the documents were lost during World War II and the fire in the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Ito ang ikalawang panunungkulan ni Mariano Abella bilang pinuno ng lalawigan — ang una ay noong panahon ng Rebolusyonaryong Pamahalaan (1898–1900). Sa pagkakataong ito, naglingkod siya sa ilalim ng pamahalaang sibil ng mga Amerikano mula 1906 hanggang 1909 bilang miyembro ng Partido Progresista. Siya ay isa sa iilang pinuno ng lalawigan na nakapaglingkod sa dalawang magkaibang rehimen — mula sa rebolusyonaryong pamahalaang Pilipino hanggang sa pamahalaang kolonyal ng mga Amerikano. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga mapagkakatiwalaang archives para kay Mariano Abella, kaya ang mga field na nauugnay sa edad (sa parehong unang termino at pagbabalik) ay nakatakdang null. Limitado rin ang lokal na tala tungkol sa panahong ito dahil bahagi ng mga dokumento ay nawala noong Ikalawang Digmaang Pandaigdig at sa sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Nag-serve sa dalawang iba\'t ibang panahon: Revolutionary Government (1898–1900) at American Civil Government (1906–1909).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 6,
                'name' => 'Mariano Perfecto',
                'image_path' => 'img/about/past-governors/Mariano Perfecto.png',
                'term_start_year' => 1910,
                'term_end_year' => 1913,
                'party' => json_encode([
                    ['term' => '1910–1913', 'party' => 'Progresista']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => 57,
                'age_at_return' => null,
                'description_en' => 'Mariano Perfecto (born 1853) served as governor of Ambos Camarines from 1910 until his death in November 1913. Age 57 is estimated based on the year of birth alone, as no exact month and day are recorded in reliable sources. Even before he became governor, he was known as a writer and journalist. He is recognized as the "Father of Bikol Literature." He founded An Parabareta (1899–1900), the first newspaper in the Bicol language, and the first printing house in the Bicol region — the Libreria y Imprenta Mariana. He died in office on November 3, 1913. His legacy in literature and printing is one of the strongest contributions of any governor to Bicolano culture.',
                'description_tl' => 'Si Mariano Perfecto (ipinanganak noong 1853) ay naglingkod bilang gobernador ng Ambos Camarines mula 1910 hanggang sa kanyang pagpanaw noong Nobyembre 1913. Ang edad na 57 ay tinatayang batay sa taon ng kapanganakan lamang, dahil walang eksaktong buwan at araw na nakatala sa mga mapagkakatiwalaang sanggunian. Bago pa man siya maging gobernador, kilala na siya bilang manunulat at mamamahayag. Siya ang kinikilalang "Ama ng Panitikang Bikol." Itinatag niya ang An Parabareta (1899–1900), ang kauna-unahang pahayagan sa wikang Bikol, at ang unang palimbagan sa rehiyon ng Bicol — ang Libreria y Imprenta Mariana. Namatay siya habang nanunungkulan noong Nobyembre 3, 1913. Ang kanyang pamana sa panitikan at limbagan ang isa sa pinakamatibay na kontribusyon ng sinumang gobernador sa kulturang Bikolano.',
                'notes' => 'Kinikilala bilang "Ama ng Panitikang Bikol." Nagtayo ng unang Bikol-language newspaper (An Parabareta) at unang printing press sa Bicol.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 7,
                'name' => 'Mariano Fuentebella',
                'image_path' => 'img/about/past-governors/Mariano Fuentebella.png',
                'term_start_year' => 1913,
                'term_end_year' => 1916,
                'party' => json_encode([
                    ['term' => '1913–1916', 'party' => 'Nacionalista']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => 62,
                'age_at_return' => null,
                'description_en' => 'Mariano Benitez Fuentebella (born 1851) served as governor of Ambos Camarines from 1913 until his death in May 1916. Age 62 is estimated based on year of birth only, as no exact month and day are recorded in reliable sources. He is from Sagñay, Camarines Sur, and previously served as gobernadorcillo of said town. He is the acknowledged patriarch of the Fuentebella family — one of the longest-running political families in the history of Camarines Sur. During his tenure, he proposed and helped secure funding for the Naga-Lagonoy Road, which is still an important thoroughfare in the province. He died in office in May 1916 and was succeeded by his son Jose.',
                'description_tl' => 'Si Mariano Benitez Fuentebella (ipinanganak noong 1851) ay naglingkod bilang gobernador ng Ambos Camarines mula 1913 hanggang sa kanyang pagpanaw noong Mayo 1916. Ang edad na 62 ay tinatayang batay sa taon ng kapanganakan lamang, dahil walang eksaktong buwan at araw na nakatala sa mga mapagkakatiwalaang sanggunian. Siya ay taga-Sagñay, Camarines Sur, at dating nanungkulan bilang gobernadorcillo ng nasabing bayan. Siya ang kinikilalang patriyarka ng pamilyang Fuentebella — isa sa pinakamatagal na pampulitikang pamilya sa kasaysayan ng Camarines Sur. Sa panahon ng kanyang panunungkulan, iminungkahi niya at natulungang makakuha ng pondo ang Naga-Lagonoy Road, na hanggang ngayon ay isang mahalagang daanan sa lalawigan. Namatay siya habang nanunungkulan noong Mayo 1916 at hinalinhan ng kanyang anak na si Jose.',
                'notes' => 'Patriyarka ng pamilyang Fuentebella. Nag-champion ng Naga-Lagonoy Road na hanggang ngayon ay major provincial road.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 8,
                'name' => 'Jose Tria Fuentebella',
                'image_path' => 'img/about/past-governors/Jose Fuentebella.png',
                'term_start_year' => 1916,
                'term_end_year' => 1916,
                'party' => json_encode([
                    ['term' => '1916', 'party' => 'Nacionalista']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => 32,
                'age_at_return' => null,
                'description_en' => 'Jose Tria Fuentebella (born June 17, 1883) is a lawyer who became governor of Ambos Camarines in 1916 after his father, Governor Mariano Fuentebella, died while in office. When he sat down, he was only 32 or 33 years old. Although his tenure as governor was short, he became a prominent legislator and political figure of Camarines Sur in the following decades. His ascension served as a continuation of leadership in the province amid the sudden absence of the sitting governor.',
                'description_tl' => 'Si Jose Tria Fuentebella (ipinanganak noong Hunyo 17, 1883) ay isang abogado na umupo bilang gobernador ng Ambos Camarines noong 1916 matapos pumanaw ang kanyang amang si Gobernador Mariano Fuentebella habang nanunungkulan. Noong siya ay umupo, siya ay 32 o 33 taong gulang pa lamang. Bagama\'t maikli ang kanyang panunungkulan bilang gobernador, siya ay naging prominenteng mambabatas at pampulitikang pigura ng Camarines Sur sa mga sumunod na dekada. Ang kanyang pag-upo ay nagsilbing pagpapatuloy ng pamumuno sa lalawigan sa gitna ng biglaang pagkawala ng nakaupong gobernador.',
                'notes' => 'Isa sa pinakamaikling termino; umupo bilang transition governor matapos ang pagkamatay ng kanyang ama.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 9,
                'name' => 'Manuel Crescini',
                'image_path' => 'img/about/past-governors/Manuel Crescini.png',
                'term_start_year' => 1916,
                'term_end_year' => 1918,
                'party' => json_encode([
                    ['term' => '1916–1918', 'party' => 'Democrata'],
                    ['term' => '1922–1928', 'party' => 'Democrata']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'This was Manuel Crescini\'s first term as governor, under the Partido Democrata, from 1916 to 1918 when the province was still Ambos Camarines. He would serve again as governor of Camarines Sur from 1922 to 1928, making him one of the few leaders who served in both Ambos Camarines and the separate Camarines Sur. Also recorded in his career is service related to the Democratic Party in the Senate. There is no documented date of birth or age recorded in reliable sources for Manuel Crescini, so the age-related fields (in both first term and return) are set to null. Records about these administrations are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Ito ang unang panunungkulan ni Manuel Crescini bilang gobernador, sa ilalim ng Partido Democrata, mula 1916 hanggang 1918 sa panahong Ambos Camarines pa ang lalawigan. Siya ay muling maglilingkod bilang gobernador ng Camarines Sur mula 1922 hanggang 1928, kaya isa siya sa iilang pinuno na naglingkod sa parehong panahon ng Ambos Camarines at ng hiwalay nang Camarines Sur. Naitala rin sa kanyang karera ang paglilingkod na may kaugnayan sa Partido Democrata sa Senado. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Manuel Crescini, kaya ang mga field na nauugnay sa edad (sa parehong unang termino at pagbabalik) ay nakatakdang null. Limitado ang mga tala tungkol sa mga administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Nag-serve sa parehong Ambos Camarines at Camarines Sur eras.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 10,
                'name' => 'Andres Garchitorena',
                'image_path' => 'img/about/past-governors/Andres Garchitorena.png',
                'term_start_year' => 1919,
                'term_end_year' => 1919,
                'party' => json_encode([
                    ['term' => '1919', 'party' => 'Democrata']
                ]),
                'era' => 'American Civil Government — Ambos Camarines',
                'era_start_year' => 1901,
                'era_end_year' => 1919,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Andres Garchitorena was the last governor of Ambos Camarines before the formal separation of the province into Camarines Norte and Camarines Sur in 1919. His son Mariano Garchitorena was also governor of Camarines Sur in 1945–1946, during the transition period after World War II. There is no documented date of birth or age recorded in reliable sources for Andres Garchitorena, so the age-related fields are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Andres Garchitorena ang huling gobernador ng Ambos Camarines bago ang pormal na paghihiwalay ng lalawigan sa Camarines Norte at Camarines Sur noong 1919. Ang kanyang anak na si Mariano Garchitorena ay naging gobernador din ng Camarines Sur noong 1945–1946, sa panahon ng transisyon pagkatapos ng Ikalawang Digmaang Pandaigdig. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Andres Garchitorena, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Huling gobernador ng Ambos Camarines bago ang separation.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 11,
                'name' => 'Julian Ocampo',
                'image_path' => 'img/about/past-governors/Julian Ocampo.png',
                'term_start_year' => 1919,
                'term_end_year' => 1922,
                'party' => json_encode([
                    ['term' => '1919–1922', 'party' => 'Nacionalista'],
                    ['term' => '1934–1935', 'party' => 'Nacionalista']
                ]),
                'era' => 'American Civil Government — Camarines Sur',
                'era_start_year' => 1919,
                'era_end_year' => 1935,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Julian Ocampo was the first governor of Camarines Sur as a separate province, after the formal division of Ambos Camarines in 1919. During his first term (1919–1922) the foundations of the new Camarines Sur provincial government were established. He served as governor again in 1934–1935. There is no documented date of birth or age recorded in reliable sources for Julian Ocampo, so the fields related to age (in both first term and return) are set to null. Records about these administrations are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Julian Ocampo ang unang gobernador ng Camarines Sur bilang hiwalay nang lalawigan, matapos ang pormal na paghahati ng Ambos Camarines noong 1919. Sa kanyang unang termino (1919–1922) naitatag ang mga pundasyon ng pamahalaang panlalawigan ng bagong Camarines Sur. Muli siyang naglingkod bilang gobernador noong 1934–1935. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Julian Ocampo, kaya ang mga field na nauugnay sa edad (sa parehong unang termino at pagbabalik) ay nakatakdang null. Limitado ang mga tala tungkol sa mga administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Unang gobernador ng Camarines Sur bilang hiwalay na lalawigan (1919).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 12,
                'name' => 'Manuel Crescini',
                'image_path' => 'img/about/past-governors/Manuel Crescini.png',
                'term_start_year' => 1922,
                'term_end_year' => 1928,
                'party' => json_encode([
                    ['term' => '1916–1918', 'party' => 'Democrata'],
                    ['term' => '1922–1928', 'party' => 'Democrata']
                ]),
                'era' => 'American Civil Government — Camarines Sur',
                'era_start_year' => 1919,
                'era_end_year' => 1935,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'This was Manuel Crescini\'s second term — this time as governor of the now-separate Camarines Sur, from 1922 to 1928. His first term was during the Ambos Camarines era (1916–1918). This six-year tenure was one of the longest continuous service in American history. There is no documented date of birth or age recorded in reliable sources for Manuel Crescini, so the age-related fields (in both first term and return) are set to null. Records about these administrations are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Ito ang ikalawang panunungkulan ni Manuel Crescini — sa pagkakataong ito bilang gobernador na ng hiwalay nang Camarines Sur, mula 1922 hanggang 1928. Ang kanyang unang termino ay noong panahon pa ng Ambos Camarines (1916–1918). Ang anim na taong panunungkulang ito ang isa sa pinakamahabang tuloy-tuloy na paglilingkod sa panahon ng mga Amerikano. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Manuel Crescini, kaya ang mga field na nauugnay sa edad (sa parehong unang termino at pagbabalik) ay nakatakdang null. Limitado ang mga tala tungkol sa mga administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Isa sa pinakamahabang single continuous term sa American era (6 years, 1922–1928).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 13,
                'name' => 'Ramon B. Felipe',
                'image_path' => 'img/about/past-governors/Ramon Felipe Sr.png',
                'term_start_year' => 1928,
                'term_end_year' => 1934,
                'party' => json_encode([
                    ['term' => '1928–1931', 'party' => 'Democrata'],
                    ['term' => '1931–1934', 'party' => 'Democrata']
                ]),
                'era' => 'American Civil Government — Camarines Sur',
                'era_start_year' => 1919,
                'era_end_year' => 1935,
                'total_terms_served' => 2,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Ramon B. Felipe served as governor of Camarines Sur for two consecutive terms: 1928–1931 and 1931–1934, under the Partido Democrata. Since his terms are consecutive, it is not considered a "return" or comeback. According to provincial government records, he was a former mayor of Iriga and later served in the Abaca Corporation of the Philippines — important because Camarines Sur was then one of the main hemp producers in the country. There is no documented date of birth or age recorded in reliable sources for Ramon B. Felipe, so the age-related fields are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Ramon B. Felipe ay naglingkod bilang gobernador ng Camarines Sur sa dalawang magkasunod na termino: 1928–1931 at 1931–1934, sa ilalim ng Partido Democrata. Dahil magkasunod ang kanyang mga termino, hindi ito itinuturing na "pagbabalik" o comeback. Ayon sa tala ng pamahalaang panlalawigan, siya ay dating alkalde ng Iriga at kalaunan ay nanungkulan sa Abaca Corporation of the Philippines — mahalaga ito dahil ang Camarines Sur ay isa noon sa mga pangunahing prodyuser ng abaka sa bansa. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Ramon B. Felipe, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 14,
                'name' => 'Julian Ocampo',
                'image_path' => 'img/about/past-governors/Julian Ocampo.png',
                'term_start_year' => 1934,
                'term_end_year' => 1935,
                'party' => json_encode([
                    ['term' => '1919–1922', 'party' => 'Nacionalista'],
                    ['term' => '1934–1935', 'party' => 'Nacionalista']
                ]),
                'era' => 'American Civil Government — Camarines Sur',
                'era_start_year' => 1919,
                'era_end_year' => 1935,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'This is the second term of office for Julian Ocampo, who previously served as the first governor of the separate Camarines Sur (1919–1922). This term served as a bridge between the American civil government and the new Commonwealth of the Philippines established in November 1935. There is no documented date of birth or age recorded in reliable sources for Julian Ocampo, so the fields related to age (in both first term and return) are set to null. Records about these administrations are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Ito ang ikalawang panunungkulan ni Julian Ocampo, na dati nang naglingkod bilang kauna-unahang gobernador ng hiwalay nang Camarines Sur (1919–1922). Ang terminong ito ang nagsilbing tulay sa pagitan ng pamahalaang sibil ng mga Amerikano at ng bagong Commonwealth ng Pilipinas na itinatag noong Nobyembre 1935. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Julian Ocampo, kaya ang mga field na nauugnay sa edad (sa parehong unang termino at pagbabalik) ay nakatakdang null. Limitado ang mga tala tungkol sa mga administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 15,
                'name' => 'Gerardo Cea',
                'image_path' => 'img/about/past-governors/Gerardo Cea.png',
                'term_start_year' => 1935,
                'term_end_year' => 1936,
                'party' => json_encode([
                    ['term' => '1935–1936', 'party' => 'Nacionalista']
                ]),
                'era' => 'Commonwealth Period',
                'era_start_year' => 1935,
                'era_end_year' => 1946,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Gerardo Cea was the first governor of Camarines Sur under the Commonwealth of the Philippines inaugurated on November 15, 1935. There is no documented date of birth or age recorded in reliable sources for Gerardo Cea, so the fields related to age are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Gerardo Cea ang unang gobernador ng Camarines Sur sa ilalim ng Commonwealth ng Pilipinas na pinasinayaan noong Nobyembre 15, 1935. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Gerardo Cea, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 16,
                'name' => 'Gabriel Prieto',
                'image_path' => 'img/about/past-governors/Gabriel Prieto.png',
                'term_start_year' => 1936,
                'term_end_year' => 1937,
                'party' => json_encode([
                    ['term' => '1936–1937', 'party' => 'Nacionalista'],
                    ['term' => '1946–1947', 'party' => 'Nacionalista']
                ]),
                'era' => 'Commonwealth Period',
                'era_start_year' => 1935,
                'era_end_year' => 1946,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'This was Gabriel Prieto\'s first term as governor, during the Commonwealth (1936–1937). He would serve again in 1946–1947, under the independent Republic of the Philippines. There is no documented date of birth or age recorded in reliable sources for Gabriel Prieto, so the fields related to age (in both first term and return) are set to null. Records about these administrations are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Ito ang unang panunungkulan ni Gabriel Prieto bilang gobernador, noong panahon ng Commonwealth (1936–1937). Muli siyang maglilingkod noong 1946–1947, sa ilalim na ng malayang Republika ng Pilipinas. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Gabriel Prieto, kaya ang mga field na nauugnay sa edad (sa parehong unang termino at pagbabalik) ay nakatakdang null. Limitado ang mga tala tungkol sa mga administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 17,
                'name' => 'Paz Cea de Conde',
                'image_path' => 'img/about/past-governors/Paz Cea de Conde.jpg',
                'term_start_year' => 1937,
                'term_end_year' => 1938,
                'party' => json_encode([
                    ['term' => '1937–1938', 'party' => 'Independent']
                ]),
                'era' => 'Commonwealth Period',
                'era_start_year' => 1935,
                'era_end_year' => 1946,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Paz Cea de Conde was a pioneer in the political history of Camarines Sur as the female governor of the province in 1937–1938, under Independent status. The period of her tenure was significant: 1937 was also the year when Filipino women gained the right to vote through a national plebiscite. So her sitting is one of the earliest examples of women\'s leadership at the provincial level in the Philippines. There is no documented date of birth or age recorded in reliable sources for Paz Cea de Conde, so the age-related fields are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Paz Cea de Conde ay isang tagapanguna sa kasaysayan ng pulitika ng Camarines Sur bilang babaeng gobernador ng lalawigan noong 1937–1938, sa ilalim ng katayuang Independent. Makabuluhan ang panahon ng kanyang panunungkulan: taong 1937 din nang makamit ng mga kababaihang Pilipino ang karapatang bumote sa pamamagitan ng pambansang plebisito. Kaya ang kanyang pag-upo ay isa sa mga pinakamaagang halimbawa ng pamumuno ng kababaihan sa antas panlalawigan sa Pilipinas. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Paz Cea de Conde, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Unang babaeng gobernador ng Camarines Sur at isa sa mga pinakaunang babaeng governor sa Pilipinas.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 18,
                'name' => 'Mariano del Gallego',
                'image_path' => 'img/about/past-governors/M Del Gallego.jpg',
                'term_start_year' => 1938,
                'term_end_year' => 1941,
                'party' => json_encode([
                    ['term' => '1938–1941', 'party' => 'Nacionalista']
                ]),
                'era' => 'Commonwealth Period',
                'era_start_year' => 1935,
                'era_end_year' => 1946,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Mariano del Gallego served as governor from 1938 to 1941 — the last peaceful years of the Commonwealth before World War II broke out in the Philippines in December 1941, which abruptly interrupted the normal course of provincial government. There is no documented date of birth or age recorded in reliable sources for Mariano del Gallego, so the age-related fields are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Mariano del Gallego ay naglingkod bilang gobernador mula 1938 hanggang 1941 — ang mga huling mapayapang taon ng Commonwealth bago sumiklab ang Ikalawang Digmaang Pandaigdig sa Pilipinas noong Disyembre 1941, na siyang biglaang pumutol sa normal na takbo ng pamahalaang panlalawigan. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Mariano del Gallego, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 19,
                'name' => 'Ramon Imperial',
                'image_path' => 'img/about/past-governors/Ramon Imperial.PNG',
                'term_start_year' => 1941,
                'term_end_year' => 1941,
                'party' => json_encode([
                    ['term' => '1941', 'party' => 'Nacionalista']
                ]),
                'era' => 'Commonwealth Period',
                'era_start_year' => 1935,
                'era_end_year' => 1946,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Ramon Imperial briefly served as governor in 1941, during the turbulent period of the Japanese invasion of the Philippines. The short-lived tenures of this year were the result of the rapid collapse of normal civil government due to the war. There is no documented date of birth or age recorded in reliable sources for Ramon Imperial, so the age-related fields are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Ramon Imperial ay panandaliang naglingkod bilang gobernador noong 1941, sa magulong panahon ng pagsalakay ng mga Hapones sa Pilipinas. Ang mga panandaliang panunungkulan sa taong ito ay bunga ng mabilis na pagbagsak ng normal na pamahalaang sibil dahil sa digmaan. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Ramon Imperial, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Isa sa pinakamaikling termino sa kasaysayan (ilang linggo lang sa 1941, wartime transition).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 20,
                'name' => 'Manuel del Gallego',
                'image_path' => 'img/about/past-governors/Manuel Del Gallego.png',
                'term_start_year' => 1941,
                'term_end_year' => 1941,
                'party' => json_encode([
                    ['term' => '1941', 'party' => 'Nacionalista']
                ]),
                'era' => 'Commonwealth Period',
                'era_start_year' => 1935,
                'era_end_year' => 1946,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Manuel del Gallego briefly served as governor in 1941, during the outbreak of World War II in the Philippines. There is no documented date of birth or age recorded in reliable sources for Manuel del Gallego, so the age-related fields are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Manuel del Gallego ay panandaliang naglingkod bilang gobernador noong 1941, sa panahon ng pagsiklab ng Ikalawang Digmaang Pandaigdig sa Pilipinas. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Manuel del Gallego, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Isa sa pinakamaikling termino sa kasaysayan (ilang linggo lang sa 1941, wartime transition).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 21,
                'name' => 'Ignacio Meliton',
                'image_path' => 'img/about/past-governors/Ignacio Meliton.png',
                'term_start_year' => 1941,
                'term_end_year' => 1942,
                'party' => json_encode([
                    ['term' => '1941–1942', 'party' => 'Nacionalista']
                ]),
                'era' => 'Commonwealth Period',
                'era_start_year' => 1935,
                'era_end_year' => 1946,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Ignacio Meliton served as governor from late 1941 to early 1942 — the last link of the Commonwealth government in the province before the Japanese occupation finally took over. Aside from politics, he is known as a teacher, historian, and museologist, and is associated with the establishment of the University of Northeastern Philippines museum. There is no documented date of birth or age recorded in reliable sources for Ignacio Meliton, so the age-related fields are set to null. Records about this administration are limited because many pre-war provincial documents were lost during World War II, and in addition to the fire at the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Ignacio Meliton ay naglingkod bilang gobernador sa pagtatapos ng 1941 hanggang sa unang bahagi ng 1942 — ang huling kawing ng pamahalaang Commonwealth sa lalawigan bago tuluyang pumalit ang pananakop ng mga Hapones. Bukod sa pulitika, siya ay kilala bilang guro, historyador, at museologist, at naiuugnay sa pagtatatag ng museo ng University of Northeastern Philippines. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Ignacio Meliton, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga tala tungkol sa administrasyong ito dahil maraming pre-war na dokumento ng lalawigan ay nawala noong Ikalawang Digmaang Pandaigdig, at dagdag pa ang sunog sa lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => 'Kilala bilang guro, historian, at museologist; nag-establish ng UNP museum.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 22,
                'name' => 'Mariano Villafuerte',
                'image_path' => 'img/about/past-governors/Mariano Villafuerte.png',
                'term_start_year' => 1942,
                'term_end_year' => 1945,
                'party' => json_encode([
                    ['term' => '1942–1945', 'party' => 'KALIBAPI']
                ]),
                'era' => 'Japanese Occupation',
                'era_start_year' => 1942,
                'era_end_year' => 1945,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Mariano Villafuerte served as governor during the Japanese occupation (1942–1945) — one of the most difficult periods in the province\'s history. Before the war, he had served as a legislator. There is no documented date of birth or age recorded in reliable sources for Mariano Villafuerte, so the age-related fields are set to null. Surviving official records from this period are very limited: the war itself was the main cause of the loss and destruction of government documents, and the remaining records were even destroyed in the burning of the old provincial capitol on June 26, 1976.',
                'description_tl' => 'Si Mariano Villafuerte ay naglingkod bilang gobernador sa panahon ng pananakop ng mga Hapones (1942–1945) — isa sa pinakamahirap na yugto ng kasaysayan ng lalawigan. Bago ang digmaan, siya ay nakapaglingkod bilang mambabatas. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Mariano Villafuerte, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Napakalimitado ng mga nakaligtas na opisyal na tala mula sa panahong ito: ang mismong digmaan ang pangunahing dahilan ng pagkawala at pagkasira ng mga dokumento ng pamahalaan, at ang mga natirang tala ay nasama pa sa pagkasunog ng lumang provincial capitol noong Hunyo 26, 1976.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 23,
                'name' => 'Mariano Garchitorena',
                'image_path' => 'img/about/past-governors/Mariano Garchitorena.png',
                'term_start_year' => 1945,
                'term_end_year' => 1946,
                'party' => json_encode([
                    ['term' => '1945–1946', 'party' => 'Liberal']
                ]),
                'era' => 'Postwar Transition',
                'era_start_year' => 1945,
                'era_end_year' => 1946,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => 47,
                'age_at_return' => null,
                'description_en' => 'Mariano Garchitorena (born February 12, 1898) served as governor of Camarines Sur from 1945 to 1946, during the critical period of civil government reconstruction after World War II. He is the son of Andres Garchitorena, the last governor of Ambos Camarines. After his tenure as governor, he rose to the national level: becoming Secretary of Agriculture and Commerce under Presidents Manuel Roxas and Elpidio Quirino (1946–1948), and later appointed Ambassador to Spain. He also held office at the Abaca Fiber Institute of the Philippines. His term coincided with the historic moment of the full independence of the Philippines on July 4, 1946.',
                'description_tl' => 'Si Mariano Garchitorena (ipinanganak noong Pebrero 12, 1898) ay naglingkod bilang gobernador ng Camarines Sur mula 1945 hanggang 1946, sa kritikal na panahon ng muling pagtatayo ng pamahalaang sibil pagkatapos ng Ikalawang Digmaang Pandaigdig. Siya ang anak ni Andres Garchitorena, ang huling gobernador ng Ambos Camarines. Pagkatapos ng kanyang panunungkulan bilang gobernador, umangat siya sa pambansang antas: naging Kalihim ng Agrikultura at Komersiyo sa ilalim nina Pangulong Manuel Roxas at Elpidio Quirino (1946–1948), at kalaunan ay hinirang na Embahador sa Espanya. Nanungkulan din siya sa Abaca Fiber Institute of the Philippines. Ang kanyang termino ay tumapat sa makasaysayang sandali ng ganap na kalayaan ng Pilipinas noong Hulyo 4, 1946.',
                'notes' => 'Naging Secretary of Agriculture and Commerce (1946–1948) at Ambassador to Spain pagkatapos ng governorship.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 24,
                'name' => 'Gabriel Prieto',
                'image_path' => 'img/about/past-governors/Gabriel Prieto.png',
                'term_start_year' => 1946,
                'term_end_year' => 1947,
                'party' => json_encode([
                    ['term' => '1936–1937', 'party' => 'Nacionalista'],
                    ['term' => '1946–1947', 'party' => 'Nacionalista']
                ]),
                'era' => 'Third Republic',
                'era_start_year' => 1946,
                'era_end_year' => 1972,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'This is the second term of office for Gabriel Prieto, who first served during the Commonwealth period (1936–1937). This time, he was one of the first governors of Camarines Sur under the independent Republic of the Philippines established on July 4, 1946. There is no documented date of birth or age recorded in reliable sources for Gabriel Prieto, so the fields related to age (both first term and return) are set to null. Surviving records about this administration are limited because on June 26, 1976, the old provincial capitol building caught fire, destroying important provincial papers and public documents.',
                'description_tl' => 'Ito ang ikalawang panunungkulan ni Gabriel Prieto, na unang naglingkod noong panahon ng Commonwealth (1936–1937). Sa pagkakataong ito, siya ang isa sa mga unang gobernador ng Camarines Sur sa ilalim ng malaya nang Republika ng Pilipinas na itinatag noong Hulyo 4, 1946. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Gabriel Prieto, kaya ang mga field na nauugnay sa edad (sa parehong unang termino at pagbabalik) ay nakatakdang null. Limitado ang mga nakaligtas na tala tungkol sa administrasyong ito dahil noong Hunyo 26, 1976, nasunog ang lumang gusali ng provincial capitol kung saan nasama sa pagkasira ang mga mahahalagang papeles at pampublikong dokumento ng probinsya.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 25,
                'name' => 'Jose del Gallego',
                'image_path' => 'img/about/past-governors/Jose Del Gallego.png',
                'term_start_year' => 1947,
                'term_end_year' => 1951,
                'party' => json_encode([
                    ['term' => '1947–1951', 'party' => 'Liberal']
                ]),
                'era' => 'Third Republic',
                'era_start_year' => 1946,
                'era_end_year' => 1972,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Jose del Gallego served as governor from 1947 to 1951, during the country\'s postwar recovery. One of his most important legacies is the establishment of the University of Northeastern Philippines (UNC), of which he was the founder and first president — an institution that continues to provide education to Bicolanos to this day. There is no documented date of birth or age recorded in reliable sources for Jose del Gallego, so the age-related fields are set to null. Surviving records about this administration are limited because on June 26, 1976, the old provincial capitol building caught fire, destroying important provincial papers and public documents.',
                'description_tl' => 'Si Jose del Gallego ay naglingkod bilang gobernador mula 1947 hanggang 1951, sa panahon ng muling pagbangon ng bansa pagkatapos ng digmaan. Ang isa sa kanyang pinakamahalagang pamana ay ang pagtatatag ng University of Northeastern Philippines (UNC), kung saan siya ang tagapagtatag at unang pangulo — isang institusyong patuloy na nagbibigay ng edukasyon sa mga Bikolano hanggang ngayon. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Jose del Gallego, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga nakaligtas na tala tungkol sa administrasyong ito dahil noong Hunyo 26, 1976, nasunog ang lumang gusali ng provincial capitol kung saan nasama sa pagkasira ang mga mahahalagang papeles at pampublikong dokumento ng probinsya.',
                'notes' => 'Founder at unang president ng University of Northeastern Philippines (UNC).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 26,
                'name' => 'Juan F. Triviño',
                'image_path' => 'img/about/past-governors/Juan Trivino.png',
                'term_start_year' => 1952,
                'term_end_year' => 1959,
                'party' => json_encode([
                    ['term' => '1952–1955', 'party' => 'Nacionalista'],
                    ['term' => '1955–1959', 'party' => 'Nacionalista']
                ]),
                'era' => 'Third Republic',
                'era_start_year' => 1946,
                'era_end_year' => 1972,
                'total_terms_served' => 2,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Juan F. Triviño served as governor of Camarines Sur for two consecutive terms from 1952 to 1959 — one of the most important tenures in the province\'s modern history. He initiated the historic transfer of the provincial capitol from Naga to Pili. After Naga became a chartered city in 1948 (Republic Act No. 305), the province needed a new seat of government. His efforts resulted in Republic Act No. 1336 enacted on June 16, 1955, which moved the capitol site to Barrio Palestina, Pili, Camarines Sur. Since then, Pili has been the capital of Camarines Sur — a status it holds to this day. This is considered one of the most important administrative decisions in the history of the province. There is no documented date of birth or age recorded in reliable sources for Juan F. Triviño, so the age-related fields are set to null. Surviving records about this administration are limited because on June 26, 1976, the old provincial capitol building caught fire, destroying important provincial papers and public documents.',
                'description_tl' => 'Si Juan F. Triviño ay naglingkod bilang gobernador ng Camarines Sur sa dalawang magkasunod na termino mula 1952 hanggang 1959 — isa sa mga pinakamahalagang panunungkulan sa modernong kasaysayan ng lalawigan. Siya ang nagpasimula ng makasaysayang paglilipat ng provincial capitol mula Naga patungong Pili. Matapos maging chartered city ang Naga noong 1948 (Republic Act No. 305), kinailangan ng lalawigan ng bagong luklukan ng pamahalaan. Ang kanyang pagsisikap ay nagbunga ng Republic Act No. 1336 na pinagtibay noong Hunyo 16, 1955, na naglipat ng capitol site sa Barrio Palestina, Pili, Camarines Sur. Mula noon, ang Pili ang naging kabisera ng Camarines Sur — isang katayuang taglay nito hanggang sa kasalukuyan. Ito ang itinuturing na isa sa pinakamahalagang desisyong administratibo sa kasaysayan ng lalawigan. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Juan F. Triviño, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga nakaligtas na tala tungkol sa administrasyong ito dahil noong Hunyo 26, 1976, nasunog ang lumang gusali ng provincial capitol kung saan nasama sa pagkasira ang mga mahahalagang papeles at pampublikong dokumento ng probinsya.',
                'notes' => 'Nag-champion ng historic transfer ng provincial capitol from Naga to Pili via RA 1336 (1955) — isa sa most significant administrative decisions sa kasaysayan ng CamSur.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 27,
                'name' => 'Apolonio Maleniza',
                'image_path' => 'img/about/past-governors/Apolonio Maleniza.png',
                'term_start_year' => 1960,
                'term_end_year' => 1967,
                'party' => json_encode([
                    ['term' => '1960–1963', 'party' => 'Liberal'],
                    ['term' => '1963–1967', 'party' => 'Liberal']
                ]),
                'era' => 'Third Republic',
                'era_start_year' => 1946,
                'era_end_year' => 1972,
                'total_terms_served' => 2,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Apolonio Maleniza served as governor for two consecutive terms. During his tenure, the project of moving the capitol to Pili was continued: on June 24, 1963, President Diosdado Macapagal issued Executive Order No. 41 that designated lands in Barrio San Jose, Pili as the new capitol site of the province. There is no documented date of birth or age recorded in reliable sources for Apolonio Maleniza, so the age-related fields are set to null. Surviving records about this administration are limited because on June 26, 1976, the old provincial capitol building caught fire, destroying important provincial papers and public documents.',
                'description_tl' => 'Si Apolonio Maleniza ay naglingkod bilang gobernador sa dalawang magkasunod na termino. Sa panahon ng kanyang panunungkulan, ipinagpatuloy ang proyekto ng paglilipat ng capitol sa Pili: noong Hunyo 24, 1963, inilabas ni Pangulong Diosdado Macapagal ang Executive Order No. 41 na nagtalaga ng mga lupain sa Barrio San Jose, Pili bilang bagong capitol site ng lalawigan. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Apolonio Maleniza, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga nakaligtas na tala tungkol sa administrasyong ito dahil noong Hunyo 26, 1976, nasunog ang lumang gusali ng provincial capitol kung saan nasama sa pagkasira ang mga mahahalagang papeles at pampublikong dokumento ng probinsya.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 28,
                'name' => 'Armando Cledera',
                'image_path' => 'img/about/past-governors/Armando Cledera.png',
                'term_start_year' => 1968,
                'term_end_year' => 1971,
                'party' => json_encode([
                    ['term' => '1968–1971', 'party' => 'Nacionalista']
                ]),
                'era' => 'Third Republic',
                'era_start_year' => 1946,
                'era_end_year' => 1972,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Armando Cledera served as governor during the final years of the Third Republic, before Martial Law was declared on September 21, 1972. There is no documented date of birth or age recorded in reliable sources for Armando Cledera, so age-related fields are set to null. Surviving records about this administration are limited because on June 26, 1976, the old provincial capitol building caught fire, destroying important provincial papers and public documents.',
                'description_tl' => 'Si Armando Cledera ay naglingkod bilang gobernador sa mga huling taon ng Ikatlong Republika, bago ideklara ang Batas Militar noong Setyembre 21, 1972. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Armando Cledera, kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga nakaligtas na tala tungkol sa administrasyong ito dahil noong Hunyo 26, 1976, nasunog ang lumang gusali ng provincial capitol kung saan nasama sa pagkasira ang mga mahahalagang papeles at pampublikong dokumento ng probinsya.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 29,
                'name' => 'Felix Alfelor Sr.',
                'image_path' => 'img/about/past-governors/Felix Alfelor.png',
                'term_start_year' => 1972,
                'term_end_year' => 1976,
                'party' => json_encode([
                    ['term' => '1972–1976', 'party' => 'Liberal']
                ]),
                'era' => 'Martial Law / Fourth Republic',
                'era_start_year' => 1972,
                'era_end_year' => 1986,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Felix Alfelor Sr. served as governor during the transition from the democratic Third Republic to the period of Martial Law declared on September 21, 1972 — a major change in the nature of governance throughout the country, including the provinces. There is no documented date of birth or age recorded in reliable sources for Felix Alfelor Sr., so the age-related fields are set to null. Surviving records about this administration are limited because on June 26, 1976, the old provincial capitol building caught fire, destroying important provincial papers and public documents.',
                'description_tl' => 'Si Felix Alfelor Sr. ay naglingkod bilang gobernador sa panahon ng transisyon mula sa demokratikong Ikatlong Republika patungo sa panahon ng Batas Militar na idineklara noong Setyembre 21, 1972 — isang malaking pagbabago sa kalikasan ng pamamahala sa buong bansa, kabilang ang mga lalawigan. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Felix Alfelor Sr., kaya ang mga field na nauugnay sa edad ay nakatakdang null. Limitado ang mga nakaligtas na tala tungkol sa administrasyong ito dahil noong Hunyo 26, 1976, nasunog ang lumang gusali ng provincial capitol kung saan nasama sa pagkasira ang mga mahahalagang papeles at pampublikong dokumento ng probinsya.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 30,
                'name' => 'Felix Abad Fuentebella',
                'image_path' => 'img/about/past-governors/Felix Fuentebella.png',
                'term_start_year' => 1976,
                'term_end_year' => 1986,
                'party' => json_encode([
                    ['term' => '1976–1986', 'party' => 'KBL']
                ]),
                'era' => 'Martial Law / Fourth Republic',
                'era_start_year' => 1972,
                'era_end_year' => 1986,
                'total_terms_served' => null,
                'times_returned' => null,
                'age_at_first_term' => 60,
                'age_at_return' => null,
                'description_en' => 'Felix Abad Fuentebella (born September 5, 1915) is a lawyer who served as governor of Camarines Sur from 1976 until the EDSA People Power Revolution in 1986 — more than ten continuous years, one of the longest tenures in the history of the province. He is the son of former Governor Mariano Fuentebella. Before becoming governor, he was the Representative of the Second District of Camarines Sur from 1953 to 1972. The number of his "terms" cannot be precisely recorded due to the peculiar arrangement of local positions during Martial Law, where appointment and election were mixed under the new system of the Marcos government. He stepped down after the EDSA People Power Revolution in 1986.',
                'description_tl' => 'Si Felix Abad Fuentebella (ipinanganak noong Setyembre 5, 1915) ay isang abogado na naglingkod bilang gobernador ng Camarines Sur mula 1976 hanggang sa EDSA People Power Revolution noong 1986 — mahigit sampung tuloy-tuloy na taon, isa sa pinakamahabang panunungkulan sa kasaysayan ng lalawigan. Siya ang anak ni dating Gobernador Mariano Fuentebella. Bago maging gobernador, siya ay Kinatawan ng Ikalawang Distrito ng Camarines Sur mula 1953 hanggang 1972. Ang bilangan ng kanyang "termino" ay hindi tiyak na maitatala dahil sa kakaibang kaayusan ng mga lokal na posisyon sa panahon ng Batas Militar, kung saan magkahalo ang appointment at halalan sa ilalim ng bagong sistema ng pamahalaang Marcos. Bumaba siya sa puwesto matapos ang EDSA People Power Revolution noong 1986.',
                'notes' => 'Pinakamahabang continuous service — 10 years (1976–1986).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 31,
                'name' => 'Luis Villafuerte Sr.',
                'image_path' => 'img/about/past-governors/Luis Villafuerte SR.png',
                'term_start_year' => 1986,
                'term_end_year' => 1992,
                'party' => json_encode([
                    ['term' => '1986–1992', 'party' => 'Lakas ng Bansa'],
                    ['term' => '1995–2004', 'party' => 'LDP']
                ]),
                'era' => 'Fifth Republic',
                'era_start_year' => 1986,
                'era_end_year' => null,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => 50,
                'age_at_return' => 59,
                'description_en' => 'Luis Robredo Villafuerte Sr. (born August 29, 1935) is a lawyer who became the governor of Camarines Sur after the EDSA People Power Revolution in 1986, under the new government of President Corazon Aquino. His first tenure (1986–1992) opened a new chapter in the province\'s politics under restored democracy and the 1987 Constitution. He was also the patriarch of the Villafuerte family which became the main political family of Camarines Sur in the following decades. He served as governor again from 1995 to 2004. In total, he recorded two separate terms in office. He passed away in September 2021.',
                'description_tl' => 'Si Luis Robredo Villafuerte Sr. (ipinanganak noong Agosto 29, 1935) ay isang abogado na naging gobernador ng Camarines Sur matapos ang EDSA People Power Revolution noong 1986, sa ilalim ng bagong pamahalaan ni Pangulong Corazon Aquino. Ang kanyang unang panunungkulan (1986–1992) ang nagbukas ng bagong kabanata sa pulitika ng lalawigan sa ilalim ng naibalik na demokrasya at ng 1987 Constitution. Siya rin ang patriyarka ng pamilyang Villafuerte na naging pangunahing pampulitikang pamilya ng Camarines Sur sa mga sumunod na dekada. Muli siyang naglingkod bilang gobernador mula 1995 hanggang 2004. Sa kabuuan, dalawang hiwalay na yugto ng panunungkulan ang kanyang naitala. Pumanaw siya noong Setyembre 2021.',
                'notes' => 'Patriarch ng Villafuerte political dynasty. Unang governor ng CamSur sa Fifth Republic. Total 15 years ng service across two stints (1986–1992, 1995–2004) — pinakamahabang overall service.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 32,
                'name' => 'Jose Bulaong',
                'image_path' => 'img/about/past-governors/Jose Bulaong.png',
                'term_start_year' => 1992,
                'term_end_year' => 1995,
                'party' => json_encode([
                    ['term' => '1992–1995', 'party' => 'Lakas']
                ]),
                'era' => 'Fifth Republic',
                'era_start_year' => 1986,
                'era_end_year' => null,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Jose Bulaong served as governor of Camarines Sur from 1992 to 1995, after winning the local elections of 1992. Before that, he served as vice governor. His term coincided with the administration of President Fidel V. Ramos. There is no documented date of birth or age recorded in reliable sources for Jose Bulaong, so the age-related fields are set to null.',
                'description_tl' => 'Si Jose Bulaong ay naglingkod bilang gobernador ng Camarines Sur mula 1992 hanggang 1995, matapos manalo sa halalang lokal ng 1992. Bago nito, siya ay nanungkulan bilang bise gobernador. Ang kanyang termino ay tumapat sa administrasyon ni Pangulong Fidel V. Ramos. Walang dokumentadong petsa ng kapanganakan o edad na nakatala sa mga reliable sources para kay Jose Bulaong, kaya ang mga field na nauugnay sa edad ay nakatakdang null.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 33,
                'name' => 'Luis Villafuerte Sr.',
                'image_path' => 'img/about/past-governors/Luis Villafuerte SR.png',
                'term_start_year' => 1995,
                'term_end_year' => 2004,
                'party' => json_encode([
                    ['term' => '1986–1992', 'party' => 'Lakas ng Bansa'],
                    ['term' => '1995–2004', 'party' => 'LDP']
                ]),
                'era' => 'Fifth Republic',
                'era_start_year' => 1986,
                'era_end_year' => null,
                'total_terms_served' => 2,
                'times_returned' => 1,
                'age_at_first_term' => 50,
                'age_at_return' => 59,
                'description_en' => 'This is the second term of office of Luis Villafuerte Sr. as governor, consisting of three consecutive elected terms: 1995–1998, 1998–2001, and 2001–2004. Between his two terms in office (1986–1992 and 1995–2004), his total service as governor reached about fifteen years — one of the longest in the province\'s history. After his tenure as governor, he served as a Representative in the House from 2004 to 2013.',
                'description_tl' => 'Ito ang ikalawang yugto ng panunungkulan ni Luis Villafuerte Sr. bilang gobernador, na binubuo ng tatlong magkakasunod na halal na termino: 1995–1998, 1998–2001, at 2001–2004. Sa pagitan ng kanyang dalawang yugto ng panunungkulan (1986–1992 at 1995–2004), umabot sa humigit-kumulang labinlimang taon ang kanyang kabuuang paglilingkod bilang gobernador — isa sa pinakamahaba sa kasaysayan ng lalawigan. Pagkatapos ng kanyang panunungkulan bilang gobernador, naglingkod siya bilang Kinatawan sa Kamara mula 2004 hanggang 2013.',
                'notes' => 'Second stint. 3 consecutive terms (1995–2004). Pinakamahabang overall service ng 15 years combined.',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 34,
                'name' => 'Luis Raymund "L-Ray" Villafuerte Jr.',
                'image_path' => 'img/about/past-governors/Luis Villafuerte.png',
                'term_start_year' => 2004,
                'term_end_year' => 2013,
                'party' => json_encode([
                    ['term' => '2004–2013', 'party' => 'Nacionalista'],
                    ['term' => '2025–present', 'party' => 'NUP']
                ]),
                'era' => 'Fifth Republic',
                'era_start_year' => 1986,
                'era_end_year' => null,
                'total_terms_served' => 4,
                'times_returned' => 1,
                'age_at_first_term' => 36,
                'age_at_return' => 57,
                'description_en' => 'Luis Raymund "L-Ray" Villafuerte Jr. (born June 3, 1968) served as governor of Camarines Sur for three consecutive terms from 2004 to 2013. During his tenure, Camarines Sur was recognized for tourism and development projects: the CamSur Watersports Complex (CWC), the promotion of Caramoan as a tourism destination, the El Verde tree-planting movement, and the construction of an IT park managed by the local government. It was also reported that the economic status of the province rose during this period. After his first three terms, he served as Representative of the Second District of Camarines Sur, and in 2025 was re-elected as governor — his fourth term overall.',
                'description_tl' => 'Si Luis Raymund "L-Ray" Villafuerte Jr. (ipinanganak noong Hunyo 3, 1968) ay naglingkod bilang gobernador ng Camarines Sur sa tatlong magkakasunod na termino mula 2004 hanggang 2013. Sa panahon ng kanyang panunungkulan, kinilala ang Camarines Sur sa mga proyektong pang-turismo at pangkaunlaran: ang CamSur Watersports Complex (CWC), ang pagtataguyod ng Caramoan bilang destinasyong pang-turismo, ang El Verde tree-planting movement, at ang pagtatayo ng IT park na pinamamahalaan ng lokal na pamahalaan. Naiulat din ang pag-angat ng katayuang pang-ekonomiya ng lalawigan sa panahong ito. Matapos ang kanyang unang tatlong termino, naglingkod siya bilang Kinatawan ng Ikalawang Distrito ng Camarines Sur, at noong 2025 ay muling nahalal bilang gobernador — ang kanyang ikaapat na termino sa kabuuan.',
                'notes' => 'Elevated CamSur from one of the poorest to one of the richest provinces. Nag-develop ng CWC at Caramoan tourism. El Verde Movement na nakakuha ng Guinness World Records. Most terms overall (4 terms total).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 35,
                'name' => 'Miguel Luis "Migz" Villafuerte',
                'image_path' => 'img/about/past-governors/Migz Villafuerte.png',
                'term_start_year' => 2013,
                'term_end_year' => 2022,
                'party' => json_encode([
                    ['term' => '2013–2022', 'party' => 'Nacionalista']
                ]),
                'era' => 'Fifth Republic',
                'era_start_year' => 1986,
                'era_end_year' => null,
                'total_terms_served' => 3,
                'times_returned' => null,
                'age_at_first_term' => 24,
                'age_at_return' => null,
                'description_en' => 'Miguel Luis "Migz" Villafuerte (born January 21, 1989) served as governor of Camarines Sur for three consecutive terms from 2013 to 2022. When he first took office in 2013 at the age of 24, he became the youngest elected governor in Philippine history — a record that garnered national attention. After his three terms as governor, he moved to the House as Representative of a district of Camarines Sur in 2022.',
                'description_tl' => 'Si Miguel Luis "Migz" Villafuerte (ipinanganak noong Enero 21, 1989) ay naglingkod bilang gobernador ng Camarines Sur sa tatlong magkakasunod na termino mula 2013 hanggang 2022. Nang una siyang maupo noong 2013 sa edad na 24, siya ang naging pinakabatang halal na gobernador sa kasaysayan ng Pilipinas — isang tala na nakakuha ng pambansang atensiyon. Pagkatapos ng kanyang tatlong termino bilang gobernador, lumipat siya sa Kamara bilang Kinatawan ng isang distrito ng Camarines Sur noong 2022.',
                'notes' => 'Pinakabatang elected governor sa Philippine history (24 years old, 2013).',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'order_no' => 36,
                'name' => 'Vincenzo Renato Luigi "Luigi" Villafuerte',
                'image_path' => 'img/about/past-governors/Luigi Villafuerte.png',
                'term_start_year' => 2022,
                'term_end_year' => 2025,
                'party' => json_encode([
                    ['term' => '2022–2025', 'party' => 'PDP–Laban']
                ]),
                'era' => 'Fifth Republic',
                'era_start_year' => 1986,
                'era_end_year' => null,
                'total_terms_served' => 1,
                'times_returned' => null,
                'age_at_first_term' => null,
                'age_at_return' => null,
                'description_en' => 'Vincenzo Renato Luigi "Luigi" Villafuerte served as governor of Camarines Sur from 2022 to 2025, as one of the province\'s youngest chief executives. He is the son of former Governor L-Ray Villafuerte Jr. and brother of former Governor Migz Villafuerte. After his term, he moved to the House as the Representative of the Second District of Camarines Sur. There is no verified official birth date record among the reliable references used in this record, so age-related fields are set to null.',
                'description_tl' => 'Si Vincenzo Renato Luigi "Luigi" Villafuerte ay naglingkod bilang gobernador ng Camarines Sur mula 2022 hanggang 2025, bilang isa sa mga pinakabatang punong ehekutibo ng lalawigan. Siya ang anak ni dating Gobernador L-Ray Villafuerte Jr. at kapatid ni dating Gobernador Migz Villafuerte. Matapos ang kanyang termino, lumipat siya sa Kamara bilang Kinatawan ng Ikalawang Distrito ng Camarines Sur. Walang na-verify na opisyal na tala ng petsa ng kapanganakan sa mga mapagkakatiwalaang sanggunian na ginamit sa talaang ito, kaya ang mga field na nauugnay sa edad ay nakatakdang null.',
                'notes' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ];

        DB::table('past_governors')->insert($governors);
    }
}
