<?php

namespace Database\Seeders;

use App\Models\SocialMediaAccount;
use Illuminate\Database\Seeder;

class SocialMediaHubSeeder extends Seeder
{
    public function run(): void
    {
        SocialMediaAccount::truncate();

        $accounts = [
            // ==========================================
            // 1. PROVINCIAL CATEGORY
            // ==========================================
            [
                'platform' => 'Facebook',
                'office_name' => 'Province of CamSur',
                'handle' => 'provinceofcamsur',
                'url' => 'https://www.facebook.com/provinceofcamsur',
                'description' => 'Official Provincial Government Facebook Page of Camarines Sur.',
                'followers_count' => '184,719 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/provinceofcamsur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Lray Villafuerte',
                'handle' => 'lrayvillafuerteofficial',
                'url' => 'https://www.facebook.com/lrayvillafuerteofficial',
                'description' => 'Official Page of Governor LRay Villafuerte.',
                'followers_count' => '264,463 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/lrayvillafuerteofficial/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Vice-Gov. Sal Fortuno Jr.',
                'handle' => 'SalFortunoJr',
                'url' => 'https://www.facebook.com/SalFortunoJr',
                'description' => 'Official Page of Vice Governor Sal Fortuno Jr.',
                'followers_count' => '13,299 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/SalFortunoJr/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 3,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Ka Fuerte Medical Assistance Program',
                'handle' => 'KaFuerteMedicalAssistance',
                'url' => 'https://www.facebook.com/KaFuerteMedicalAssistance',
                'description' => 'Provincial health aid and medical assistance program.',
                'followers_count' => '46,369 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/KaFuerteMedicalAssistance/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Serbisyong Ka Fuerte',
                'handle' => 'SerbisyongKaFuerte',
                'url' => 'https://www.facebook.com/SerbisyongKaFuerte',
                'description' => 'Official public service outreach of the Provincial Government.',
                'followers_count' => '51,450 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/SerbisyongKaFuerte/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Luigi Villafuerte',
                'handle' => 'luigi.villafuerte.39',
                'url' => 'https://www.facebook.com/luigi.villafuerte.39',
                'description' => 'Official Public Page of Luigi Villafuerte.',
                'followers_count' => '125,909 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/luigi.villafuerte.39/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Congressman Migz Villafuerte',
                'handle' => 'villafuertemigz',
                'url' => 'https://www.facebook.com/villafuertemigz',
                'description' => 'Official Page of Congressman Migz Villafuerte.',
                'followers_count' => '439,986 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/villafuertemigz/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 7,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur TV',
                'handle' => 'CamSurTV',
                'url' => 'https://www.facebook.com/CamSurTV',
                'description' => 'Official Provincial Television & Broadcasting Channel of Camarines Sur.',
                'followers_count' => '42,800 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/CamSurTV/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 8,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Modern CamSur',
                'handle' => 'moderncamsur',
                'url' => 'https://www.facebook.com/moderncamsur',
                'description' => 'Showcasing modernization and infrastructure developments in Camarines Sur.',
                'followers_count' => '19,400 followers',
                'badge_category' => 'Provincial',
                'avatar_url' => 'https://graph.facebook.com/moderncamsur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],

            // ==========================================
            // 2. DEPARTMENTS CATEGORY
            // ==========================================
            [
                'platform' => 'Facebook',
                'office_name' => 'Sangguniang Panlalawigan ng Camarines Sur',
                'handle' => 'camsursp',
                'url' => 'https://www.facebook.com/camsursp',
                'description' => 'Official Legislative Body of the Province of Camarines Sur.',
                'followers_count' => '2,222 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/camsursp/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 10,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Camsur Peso',
                'handle' => 'camsur.peso',
                'url' => 'https://www.facebook.com/camsur.peso',
                'description' => 'Public Employment Service Office of Camarines Sur.',
                'followers_count' => '49,129 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/camsur.peso/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 11,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Edmero Camarines Sur',
                'handle' => 'EdmeroCamSur',
                'url' => 'https://www.facebook.com/EdmeroCamSur',
                'description' => 'Education Development and Management Resource Office.',
                'followers_count' => '64,760 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/EdmeroCamSur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Camarines Sur Provincial Health Office',
                'handle' => 'phocamsur',
                'url' => 'https://www.facebook.com/phocamsur',
                'description' => 'Official Public Health Office of the Province of Camarines Sur.',
                'followers_count' => '2,634 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/phocamsur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'PSWDO-Camarines Sur',
                'handle' => 'PSWDOCamarinesSur',
                'url' => 'https://www.facebook.com/PSWDOCamarinesSur',
                'description' => 'Provincial Social Welfare and Development Office.',
                'followers_count' => '715 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/PSWDOCamarinesSur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 14,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur Animation',
                'handle' => 'camsuranimationstudio',
                'url' => 'https://www.facebook.com/camsuranimationstudio',
                'description' => 'Camarines Sur Digital Arts and Animation Hub.',
                'followers_count' => '2,573 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/camsuranimationstudio/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 15,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Tubig To Handle PH',
                'handle' => 'tubigtohandleph',
                'url' => 'https://www.facebook.com/tubigtohandleph',
                'description' => 'Official Provincial Clean Water Infrastructure & Supply Project.',
                'followers_count' => '18,500 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/tubigtohandleph/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 16,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur Express',
                'handle' => '100086359266881',
                'url' => 'https://www.facebook.com/people/Cam-Sur-Express/100086359266881',
                'description' => 'Provincial Logistics & Rapid Public Transport Service.',
                'followers_count' => '24,100 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/100086359266881/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 17,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur PIAO',
                'handle' => 'camsurpiao',
                'url' => 'https://www.facebook.com/camsurpiao',
                'description' => 'Provincial Information and Public Assistance Office.',
                'followers_count' => '15,200 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/camsurpiao/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 18,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur POP',
                'handle' => 'camsurpop',
                'url' => 'https://www.facebook.com/camsurpop',
                'description' => 'Provincial Population & Family Development Office.',
                'followers_count' => '8,900 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/camsurpop/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 19,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Draw CamSur',
                'handle' => 'drawcamsur',
                'url' => 'https://www.facebook.com/drawcamsur',
                'description' => 'Official Arts & Creative Cultural Initiatives Hub of Camarines Sur.',
                'followers_count' => '11,300 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/drawcamsur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 20,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur Agriculture Services',
                'handle' => '61573831063065',
                'url' => 'https://www.facebook.com/profile.php?id=61573831063065',
                'description' => 'Official Agricultural Assistance & Extension Services Page.',
                'followers_count' => '5,400 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/61573831063065/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 21,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur Public Assistance',
                'handle' => '61556512632216',
                'url' => 'https://www.facebook.com/profile.php?id=61556512632216',
                'description' => 'Provincial Public Welfare Services & Community Outreach.',
                'followers_count' => '6,100 followers',
                'badge_category' => 'Departments',
                'avatar_url' => 'https://graph.facebook.com/61556512632216/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 22,
            ],

            // ==========================================
            // 3. TOURISM CATEGORY
            // ==========================================
            [
                'platform' => 'Facebook',
                'office_name' => 'Visit CamSur',
                'handle' => 'VisitCamSur',
                'url' => 'https://www.facebook.com/VisitCamSur',
                'description' => 'Official Tourism Channel of Camarines Sur.',
                'followers_count' => '120,325 followers',
                'badge_category' => 'Tourism',
                'avatar_url' => 'https://graph.facebook.com/VisitCamSur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 23,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Fuerte CamSur Sports Complex',
                'handle' => 'FuerteCamSurSportsComplex',
                'url' => 'https://www.facebook.com/FuerteCamSurSportsComplex',
                'description' => 'Premiere sports complex in Camarines Sur.',
                'followers_count' => '7,923 followers',
                'badge_category' => 'Tourism',
                'avatar_url' => 'https://graph.facebook.com/FuerteCamSurSportsComplex/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 24,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CWC (CamSur Watersports Complex)',
                'handle' => 'cwcwakepark',
                'url' => 'https://www.facebook.com/cwcwakepark',
                'description' => 'World-class wakeboarding and watersports destination.',
                'followers_count' => '88,002 followers',
                'badge_category' => 'Tourism',
                'avatar_url' => 'https://graph.facebook.com/cwcwakepark/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 25,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Pili Grove Golf Club',
                'handle' => 'PiliGroveGolfClub',
                'url' => 'https://www.facebook.com/PiliGroveGolfClub',
                'description' => 'Golf and recreation facility in Pili, Camarines Sur.',
                'followers_count' => '3,316 followers',
                'badge_category' => 'Tourism',
                'avatar_url' => 'https://graph.facebook.com/PiliGroveGolfClub/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 26,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur Adventure',
                'handle' => 'camsuradventure',
                'url' => 'https://www.facebook.com/camsuradventure',
                'description' => 'Official Outdoor Eco-Adventures & Trail Tours in Camarines Sur.',
                'followers_count' => '16,700 followers',
                'badge_category' => 'Tourism',
                'avatar_url' => 'https://graph.facebook.com/camsuradventure/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 27,
            ],

            // ==========================================
            // 4. EVENTS CATEGORY
            // ==========================================
            [
                'platform' => 'Facebook',
                'office_name' => 'Kaogma Festival',
                'handle' => 'kaogmafestival',
                'url' => 'https://www.facebook.com/kaogmafestival',
                'description' => 'The hottest festival in the world - official Facebook page.',
                'followers_count' => '95,400 followers',
                'badge_category' => 'Events',
                'avatar_url' => 'https://graph.facebook.com/kaogmafestival/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 28,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'Miss Kaogma',
                'handle' => '100091710882715',
                'url' => 'https://www.facebook.com/people/Miss-Kaogma/100091710882715/',
                'description' => 'Official Page of the prestigious Miss Kaogma Pageant.',
                'followers_count' => '38,200 followers',
                'badge_category' => 'Events',
                'avatar_url' => 'https://graph.facebook.com/100091710882715/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => true,
                'sort_order' => 29,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => '5150 Triathlon CamSur',
                'handle' => '5150camsur',
                'url' => 'https://www.facebook.com/5150camsur',
                'description' => 'International 5150 Triathlon competition in Camarines Sur.',
                'followers_count' => '14,200 followers',
                'badge_category' => 'Events',
                'avatar_url' => 'https://graph.facebook.com/5150camsur/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 30,
            ],
            [
                'platform' => 'Facebook',
                'office_name' => 'CamSur Pickleball',
                'handle' => 'camsurpickleball',
                'url' => 'https://www.facebook.com/camsurpickleball',
                'description' => 'Official CamSur Pickleball Sports Club & Tournament Updates.',
                'followers_count' => '9,800 followers',
                'badge_category' => 'Events',
                'avatar_url' => 'https://graph.facebook.com/camsurpickleball/picture?type=large',
                'color_hex' => '#1877F2',
                'is_verified' => true,
                'is_featured' => false,
                'sort_order' => 31,
            ],
        ];

        foreach ($accounts as $account) {
            SocialMediaAccount::create($account);
        }
    }
}