<?php

use Illuminate\Support\Facades\Route;

// 1. Guest Main Page (home.blade.php under pages/guest)
Route::get('/', function () {
    return view('pages.guest.home');
})->name('home');

// 2. Authenticated Dashboard Page (dashboard.blade.php under pages/authenticated)
Route::get('/dashboard', function () {
    return view('pages.authenticated.dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Auth routes generated by Laravel Breeze (Login, Register, Profile, etc.)
require __DIR__.'/auth.php';
